version: "3"

set: [errexit, nounset]

vars:
  DATA_HOME: { sh: "echo ${XDG_DATA_HOME:-~/.local/share}" }
  CONFIG_HOME: { sh: "echo ${XDG_CONFIG_HOME:-~/.config}" }
  FNF_DATA_DIR: "{{.DATA_HOME}}/fnf"
  FNF_CONFIG_DIR: "{{.CONFIG_HOME}}/fnf"
  INSTALL_DIR: { sh: "echo ${HOME}/.local/bin" }
  MISE_VERSION: 2025.12.13

silent: true

tasks:
  default:
    deps: [setup]
    cmd: { task: sync }

  setup:
    desc: Setup all.
    deps: [setup:config]
    cmds:
      - task: setup:mise

  setup:taskfile:
    cmds:
      - echo "Installing Taskfile {{.TASKFILE_VERSION}}"
      - curl -LSs https://github.com/go-task/task/releases/download/{{.TASKFILE_VERSION}}/task_linux_amd64.tar.gz | tar -C {{.INSTALL_DIR}} -xz task
    status: ['[ "v$(task --version)" = "{{.TASKFILE_VERSION}}" ]']

  setup:webi:
    cmd: curl -sS https://webi.sh/webi | sh
    status: [webi]

  setup:mise:
    env:
      MISE_VERSION: "{{.MISE_VERSION}}"
      MISE_INSTALL_PATH: "{{.INSTALL_DIR}}/mise"
    cmd: curl https://mise.run | sh
    status: ['[ "$(${MISE_INSTALL_PATH} version --quiet | tail | awk ''{print $1}'')" = "${MISE_VERSION}" ]']

  setup:config:
    run: once
    cmds:
      - "[ -d {{.INSTALL_DIR}} ] || mkdir -p {{.INSTALL_DIR}}"
      - "[ -d {{.FNF_CONFIG_DIR}}/current ] || mkdir -p {{.FNF_CONFIG_DIR}}/current"

      # Set up defaults
      - "[ -d {{.FNF_CONFIG_DIR}}/current/theme ] || ln -snf {{.FNF_DATA_DIR}}/themes/catppuccin-mocha {{.FNF_CONFIG_DIR}}/current/theme"

      - "[ -d {{.CONFIG_HOME}}/btop/themes ] || mkdir -p {{.CONFIG_HOME}}/btop/themes"
      - "[ -f {{.CONFIG_HOME}}/btop/themes/current.theme ] || ln -snf {{.FNF_DATA_DIR}}/themes/catppuccin-mocha/btop.theme {{.CONFIG_HOME}}/btop/themes/current.theme"
      - "[ -f {{.FNF_CONFIG_DIR}}/hyprland.conf ] || touch {{.FNF_CONFIG_DIR}}/hyprland.conf"

  setup:zsh:
    cmds:
      - sudo apt install -qqy zsh
      - defer: echo "Changing default shell to zsh" && chsh -s $(which zsh)
    status: [zsh --version]

  setup:oh-my-zsh:
    deps: [setup:zsh]
    cmds:
      - echo "Installing oh-my-zsh"
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    status: ["test -d ${HOME}/.oh-my-zsh"]

  setup:oh-my-posh:
    cmds:
      - echo "Installing oh-my-posh {{.OH_MY_POSH_VERSION}}"
      - curl -s https://ohmyposh.dev/install.sh | bash -s -- -d {{.INSTALL_DIR}} -v {{.OH_MY_POSH_VERSION}}
    status:
      - '[ "v$(oh-my-posh version)" = "{{.OH_MY_POSH_VERSION}}" ]'

  setup:go:
    cmds:
      - echo "Removing /usr/local/go if any"
      - sudo rm -rf /usr/local/go
      - echo "Installing go {{.GO_VERSION}}"
      - curl -LSs https://go.dev/dl/go{{.GO_VERSION}}.linux-amd64.tar.gz | sudo tar -C /usr/local -xz
    status:
      - '[ $(go version | awk ''{print $3}'' | sed ''s/^go//'') = "{{.GO_VERSION}}" ]'

  sync:
    desc: Sync all configurations.
    deps:
      - task: _sync:k9s
      - task: _sync:zsh
      - task: _sync:zellij
      - task: _sync:lazygit
      - task: _sync:lazydocker
      - task: _sync:oh-my-posh
      - task: _sync:nvim
      - task: _sync:tmux
        vars:
          DELETE: "0"
      - task: _sync:kitty
      - task: _sync:hypr
      - task: _sync:uwsm
      - task: _sync:fontconfig
      - task: _sync:waybar
      - task: _sync:wofi
      - task: _sync:ghostty
      - task: _sync:swaync
      - task: _sync:rofi
      - task: _sync:yazi
      - task: _sync:alacritty
        vars: { DIR: "~" }
      - task: _syncfile:.config/btop/btop.conf
        vars: { DIR: "~" }
      - task: _syncfile:.config/walker/config.toml
        vars: { DIR: "~" }
      - task: _syncfile:.config/walker/themes/default.css
        vars: { DIR: "~" }
      - task: _syncfile:.config/walker/themes/macchiato.css
        vars: { DIR: "~" }
      - task: _syncfile:.config/walker/themes/macchiato.toml
        vars: { DIR: "~" }
      - task: _sync:opencode/agent
      - task: _syncfile:.config/opencode/opencode.json
        vars: { DIR: "~" }
      - task: _syncfile:.zshrc
        vars: { DIR: { sh: "echo ${HOME}" } }
      - task: _syncfile:.inputrc
        vars: { DIR: { sh: "echo ${HOME}" } }
      - task: _syncfile:.bash_profile
        vars: { DIR: { sh: "echo ${HOME}" } }
      - task: _sync:bin
        vars:
          DIR: "{{.FNF_DATA_DIR}}"
          SRC: "{{.ROOT_DIR}}/.local/share/bin/"
      - task: _sync:themes
        vars:
          DIR: "{{.FNF_DATA_DIR}}"
          SRC: "{{.ROOT_DIR}}/themes/"
      - task: _sync:applications
        vars:
          DIR: "{{.DATA_HOME}}"
          SRC: "{{.ROOT_DIR}}/.local/share/applications/"
          DELETE: "0"
      - task: _sync:icons
        vars:
          DIR: "{{.DATA_HOME}}"
          SRC: "{{.ROOT_DIR}}/.local/share/icons/"
          DELETE: "0"

  _sync:*:
    vars:
      CONFIG: "{{index .MATCH 0}}"
      DIR: "{{.DIR | default .CONFIG_HOME}}"
      SRC: '{{.SRC | default (printf "%s/.config/%s/" .ROOT_DIR .CONFIG)}}'
      DELETE: '{{.DELETE | default "1"}}'
    label: _sync:{{.CONFIG}}
    cmds:
      - echo "Syncing configuration for {{.CONFIG}} to {{.DIR}}/{{.CONFIG}}/"
      - rsync
        --quiet
        --recursive
        {{if eq .DELETE "1"}}
        --delete
        {{end}}
        --mkpath
        {{.SRC}}
        {{.DIR}}/{{.CONFIG}}/
    internal: true
    ignore_error: true

  _syncfile:*:
    requires:
      vars: [DIR]
    vars:
      FILE: "{{index .MATCH 0}}"
    label: _syncfile:{{.FILE}}
    cmds:
      - echo "Syncing {{.FILE}} to {{.DIR}}/{{.FILE}}"
      - rsync --quiet {{.ROOT_DIR}}/{{.FILE}} {{.DIR}}/{{.FILE}}
    internal: true
    ignore_error: true
