# Set maximum authentication retries to prevent brute force attacks
MaxAuthTries 3

# Disallow connecting using empty passwords
PermitEmptyPasswords no

# Prevent root from being logged in via SSH
PermitRootLogin no

# Enable pubkey authentication
PubkeyAuthentication yes

# Force key only. Stop password brute force.
PasswordAuthentication no

# Disable keyboard-interactive authentication
KbdInteractiveAuthentication no

# Block forwarding risks
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no

# Number of client alive messages sent without client responding
ClientAliveCountMax 2

# Send a keepalive message to the client when the session has been idle for 300 seconds. This prevents/detects
# connection timeouts
ClientAliveInterval 300
