general {
    col.active_border = rgb(1e66f5) rgb(8839ef) 45deg
    col.inactive_border = rgb(eff1f5)
}

decoration {
    shadow {
        color = rgb(dce0e8)
    }
}

group {
    col.border_active = rgb(1e66f5) rgb(8839ef) 45deg
    col.border_inactive = rgb(eff1f5)

    groupbar {
        col.active = rgb(7287fd)
        text_color = rgb(4c4f69)
    }
}
