rosewater="#dc8a78"
flamingo="#dd7878"
pink="#ea76cb"
mauve="#8839ef"
red="#d20f39"
maroon="#e64553"
peach="#fe640b"
yellow="#df8e1d"
green="#40a02b"
teal="#179299"
sky="#04a5e5"
sapphire="#209fb5"
blue="#1e66f5"
lavender="#7287fd"
text="#4c4f69"
subtext1="#5c5f77"
subtext0="#6c6f85"
overlay2="#7c7f93"
overlay1="#8c8fa1"
overlay0="#9ca0b0"
surface2="#acb0be"
surface1="#bcc0cc"
surface0="#ccd0da"
base="#eff1f5"
mantle="#e6e9ef"
crust="#dce0e8"

colour_fg="$text"
colour_secondary_fg="$blue"
colour_bg="default"
colour_unavailable_fg="$surface1"
colour_client_prefix_bg="$green"
colour_client_prefix_none_bg="$pink"

colour_focused_pane_bg="$surface1"

colour_mode_fg="$colour_fg"
colour_mode_bg="$surface1"

colour_pane_border="$surface1"
colour_pane_active_border="$blue"
colour_pane_in_mode_border="$yellow"
colour_pane_synchronized_border="$red"

colour_pane_indicator="$blue"
colour_pane_active_indicator="$mauve"

colour_message_command_fg="$base"
colour_message_command_bg="$colour_fg"

colour_window_status_fg="$surface1"
colour_window_status_secondary_fg="$colour_secondary_fg"
colour_window_status_current_fg="$colour_fg"
colour_window_status_current_secondary_fg="$colour_secondary_fg"
colour_window_status_bell_fg="$yellow"
colour_window_status_bell_bg="default"
colour_window_status_last_fg="$surface1"
colour_window_status_last_bg="default"
colour_window_status_zoomed_fg="$mauve"
