# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = uwsm app -- kitty
$fileManager = uwsm app -- dolphin
$menu = uwsm app -- rofi -show drun
$serviceMenu = uwsm app -- uuctl rofi
$browser = uwsm app -- brave
$lock = uwsm app -- hyprlock
$webapp = $browser --new-window --app
$nc = swaync-client --toggle-panel
$fnfMenu = uwsm app -- ~/.local/share/fnf/bin/fnf-menu
$top = $terminal sh -c 'btop'

$hyprshot = uwsm app -- hyprshot
$sattyEditStdin = uwsm app -- satty --actions-on-right-click save-to-clipboard --filename -
$ocr4 = uwsm app -- OCR4Linux.sh -l --lang all
